version: 0.2

phases:

  pre_build:
    commands:
      - rm -rf .python-version
  build:
    commands:
      - terraform init
      - terraform apply -auto-approve
artifacts:
  name: scanned_source
  packaging: zip
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR