version: 0.2

phases:

  pre_build:
    commands:
      - rm -rf .python-version
  build:
    commands:
      - checkov --directory cdk.out --config-file ./rules/checkov/checkov-config.yml
      - cfn-guard validate -d cdk.out/policy-as-code.template.json -r ./rules/cfn-guard
artifacts:
  name: scanned_source
  packaging: zip
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR